# Generated by Django 5.0.4 on 2024-04-27 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_customer', models.CharField(max_length=100)),
                ('address_customer', models.TextField()),
                ('phone_number_customer', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('email_customer', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Manufacturer_product', models.TextField()),
                ('name_product', models.CharField(max_length=100)),
                ('description_product', models.TextField()),
                ('purchase_date', models.DateField()),
                ('warranty_period', models.IntegerField(choices=[(12, '12 months'), (24, '24 months')])),
                ('warranty_product', models.BooleanField(default=True)),
                ('requires_repair', models.BooleanField(default=True)),
                ('fault_status', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Warranty.customer')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(null=True)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
