# Generated by Django 5.0.4 on 2024-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Manufacturer_product',
            field=models.CharField(max_length=100),
        ),
    ]
