# Generated by Django 5.0.4 on 2024-04-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty', '0003_alter_product_requires_repair_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='warranty_product',
            field=models.IntegerField(choices=[(0, 'Hết bảo hành'), (1, 'Còn bảo hành')]),
        ),
    ]
