# Generated by Django 5.0.4 on 2024-05-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty', '0006_repair'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
